name: Delete Azure Resources

on:
  workflow_dispatch:

jobs:
  delete-resources:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: |
          az group delete --name myterraform --yes


