name: Terraform Apply
 
on:
  push:
    branches:
    - main
  
 
jobs:
  terraform:
    name: 'Terraform'
     runs-on: ubuntu-latest

     env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    

      steps:
       -uses: actions/checkout@v2
 
       - name: 'Setup Terraform
         uses: hashicorp/setup.terraform@v1
  
       - name: 'Setup Terraform
         uses: hashicorp/setup.terraform@v1
         
       